services:
  backend:
    build: ./backend
    container_name: miniupload-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - miniupload-net

  frontend:
    image: php:8.2-apache
    container_name: miniupload-frontend
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
      - ./frontend/php.ini:/usr/local/etc/php/php.ini
      - ./frontend/apache.conf:/etc/apache2/sites-available/000-default.conf
      - /tmp/php-sessions:/var/lib/php/sessions
    depends_on:
      - backend
    networks:
      - miniupload-net


  db:
    image: mariadb:11
    container_name: miniuploaddb
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=miniupload_db
      - MARIADB_USER=miniupload
      - MARIADB_PASSWORD=miniupload
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - miniupload-net

volumes:
  db_data:

networks:
  miniupload-net:
    driver: bridge